from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usdt_wallet_address', models.CharField(blank=True, max_length=128)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('momo_number', models.CharField(max_length=50)),
                ('country', models.CharField(default='GH', max_length=2)),
                ('balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('asset_name', models.CharField(max_length=64)),
                ('network', models.CharField(max_length=32)),
                ('wallet_address', models.CharField(blank=True, max_length=256)),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(max_length=20)),
                ('crypto_symbol', models.CharField(default='USDT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_monitored', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='api.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(default='buy', max_length=10)),
                ('crypto_amount', models.FloatField()),
                ('crypto_symbol', models.CharField(default='USDT', max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('crypto_address_used', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('fiat_amount', models.FloatField(blank=True, null=True)),
                ('fiat_currency', models.CharField(default='GHS', max_length=3)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('rate_used', models.FloatField(blank=True, null=True)),
                ('coinvibe_fee', models.FloatField(default=0.0)),
                ('network_fee', models.FloatField(default=0.0)),
                ('vendor_receives', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_status', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.vendor')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount_ghs', models.FloatField()),
                ('rate_usd_to_ghs', models.FloatField()),
                ('usdt_amount', models.FloatField()),
                ('fee_percent', models.FloatField(default=0.0)),
                ('fee_ghs', models.FloatField(default=0.0)),
                ('total_charge_ghs', models.FloatField()),
                ('network', models.CharField(max_length=20)),
                ('recipient_address', models.CharField(max_length=255)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('momo_number', models.CharField(blank=True, max_length=50, null=True)),
                ('momo_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.vendor')),
            ],
        ),
    ]
