# Generated by Django 5.2.8 on 2025-12-02 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_blockchain_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngn_to_ghs_rate', models.FloatField(default=0.0043)),
                ('ghs_to_ngn_rate', models.FloatField(default=230.0)),
                ('fee_percent', models.FloatField(default=2.0)),
                ('min_exchange_ghs', models.FloatField(default=100.0)),
                ('max_exchange_ghs', models.FloatField(default=10000.0)),
                ('min_exchange_ngn', models.FloatField(default=50000.0)),
                ('max_exchange_ngn', models.FloatField(default=5000000.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=100, unique=True)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('from_amount', models.FloatField()),
                ('to_amount', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('fee_amount', models.FloatField()),
                ('recipient_details', models.JSONField(default=dict)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='api.vendor')),
            ],
        ),
    ]
