# Generated by Django 5.2.8 on 2025-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exchangerate_currencyexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='buy_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable buying for this asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='buy_fee_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Service fee percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='buy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Buy rate in GHS per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='min_buy_amount_usd',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum buy amount in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_fee_usd',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Fixed network fee in USD', max_digits=10),
        ),
    ]
