# Generated by Django 5.2.8 on 2025-12-04 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_asset_buy_enabled_asset_buy_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asset'),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='asset_symbol',
            field=models.CharField(default='USDT', max_length=16),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='network_fee_ghs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
