# Generated by Django 5.2.8 on 2025-12-08 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buyorder_admin_notes_buyorder_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngn_bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('ngn_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('ngn_account_name', models.CharField(blank=True, default='', max_length=100)),
                ('ghs_momo_number', models.CharField(blank=True, default='', max_length=20)),
                ('ghs_momo_name', models.CharField(blank=True, default='', max_length=100)),
                ('ghs_momo_network', models.CharField(blank=True, default='MTN', max_length=20)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Exchange Payment Settings',
                'verbose_name_plural': 'Exchange Payment Settings',
            },
        ),
    ]
