# Generated by Django 5.2.8 on 2025-12-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emailverification_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exchangepaymentsettings',
            name='ghs_account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exchangepaymentsettings',
            name='ghs_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='exchangepaymentsettings',
            name='ghs_bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
