# Generated by Django 5.2.8 on 2026-01-27 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_buyorder_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(help_text="User's review comment")),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this review on homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('buy_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.buyorder')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.transaction')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('vendor', 'transaction'), name='unique_transaction_review'), models.UniqueConstraint(condition=models.Q(('buy_order__isnull', False)), fields=('vendor', 'buy_order'), name='unique_buy_order_review')],
            },
        ),
    ]
